version: "3.8"

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Elixir Version: Updated to match project requirements
        VARIANT: "1.15.4"
        # Phoenix Version: Updated to match project requirements
        PHOENIX_VERSION: "1.7.0"
        # Node Version: Updated to match production
        NODE_VERSION: "20"

    volumes:
      - ..:/workspace:z
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    environment:
      MOBILIZON_INSTANCE_NAME: My Mobilizon Instance
      MOBILIZON_INSTANCE_HOST: localhost
      MOBILIZON_INSTANCE_HOST_PORT: 4000
      MOBILIZON_INSTANCE_PORT: 4000
      MOBILIZON_INSTANCE_EMAIL: noreply@mobilizon.me
      MOBILIZON_INSTANCE_REGISTRATIONS_OPEN: "true"
      MOBILIZON_DATABASE_PASSWORD: postgres
      MOBILIZON_DATABASE_USERNAME: postgres
      MOBILIZON_DATABASE_DBNAME: mobilizon
      MOBILIZON_DATABASE_HOST: db
      MOBILIZON_SMTP_SERVER: email-smtp.eu-north-1.amazonaws.com
      MOBILIZON_SMTP_PORT: 587
      MOBILIZON_SMTP_USERNAME: AKIAQIDHXO7DPX3OANND
      MOBILIZON_SMTP_PASSWORD: BMdIY5hSPcUK1OO+ya4VAfPVgQQlLQFladHWovoa47su

  db:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

volumes:
  postgres-data: null
